services:

  api:
    container_name: primefix-api
    build:
      context: .
      dockerfile: PrimeFixPlatform.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=prime_fix_web_db;Username=postgres;Password=123456;"
      TokenSettings__Secret: "dev-secret-key"
    depends_on:
      - db
    networks:
      - primefix-net

  db:
    container_name: primefix-db
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: prime_fix_web_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - primefix-net

  pgadmin:
    container_name: primefix-pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    depends_on:
      - db
    networks:
      - primefix-net

networks:
  primefix-net:

volumes:
  postgres_data: